version: '3'
services:
  php-fpm:
    build:
      context: images-drupal7/${PROJECT_PHP}
    container_name: "${PROJECT_NAME}-php-fpm"
    volumes:
      - ../${PROJECT_NAME}:/drupal
    labels:
      - "traefik.enable=false"
    networks:
      - default
      - project-network

  web:
    image: nginx:alpine
    container_name: "${PROJECT_NAME}-web"
    working_dir: /drupal
    expose:
      - '80'
    volumes:
      - ../${PROJECT_NAME}:/drupal
      - ./nginx-drupal.default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - SERVER_NAME=${PROJECT_NAME}.my-docker.localhost
    links:
      - php-fpm
    labels:
      - traefik.http.routers.${PROJECT_WEB}.rule=Host(`${PROJECT_WEB}.my-docker.localhost`)
    depends_on:
      - php-fpm
    networks:
      - default
      - project-network

networks:
  default:
    external:
      name: common-traefik

  project-network:
    name: ${PROJECT_NAME}-network
    internal: true
